# Generated by Django 5.2.5 on 2025-09-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dado_baja',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('contador', 'Contador'), ('auditor', 'Auditor')], default='auditor', max_length=50),
        ),
    ]
