# Generated by Django 5.2.5 on 2025-09-14 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_cuentas', '0004_alter_cuenta_codigo_alter_cuenta_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
