# Generated by Django 5.2.5 on 2025-09-21 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan_cuentas', '0006_rename_saldo_inicial_cuenta_saldo_actual_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movimiento',
        ),
    ]
