# Generated by Django 5.2.5 on 2025-09-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='saldo_actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='saldo_inicial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
