# Generated by Django 5.2.5 on 2025-09-09 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_cuentas', '0002_cuenta_saldo_actual_cuenta_saldo_inicial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='saldo_actual',
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('debe', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('haber', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='plan_cuentas.cuenta')),
            ],
        ),
    ]
