# Generated by Django 5.2.5 on 2025-09-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_cuentas', '0005_cuenta_activo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuenta',
            old_name='saldo_inicial',
            new_name='saldo_actual',
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='tipo',
            field=models.CharField(choices=[('activo', 'Activo'), ('pasivo', 'Pasivo'), ('patrimonio', 'Patrimonio'), ('resultado_positivo', 'Resultado positivo'), ('resultado_negativo', 'Resultado negativo')], max_length=20),
        ),
    ]
